### ISSUE TITLE
Tag Cloud is not working with PJS.Bootstrap Theme

### ISSUE THREAD

**Issue by RajneeshVerma** [psenechal/PJS.Bootstrap#1]
I have installed Orchard Orchard v.1.9.1.0 with Theme PJS.Bootstrap 2015 but i can see thag cloud are as below: 

Tag Cloud 

ADO.NET 
Adobe 
Ajax 
anglebrackets 
Angular 
AngularJS 
Animations 
Apple 
Architecture 
ASP.NET 
ASP.NET AJAX 
ASP.NET MVC 
ASP.NET Web API 
Azure 
Babel 
Breeze 
With PJS.Bootstrap Theme(Wrong)
![tag 1](https://cloud.githubusercontent.com/assets/5612153/9704782/0dc1b16e-54d0-11e5-80e1-e79c5c2fc272.PNG)

With Default Theme (Correct)
![tag 2](https://cloud.githubusercontent.com/assets/5612153/9704784/1317baf0-54d0-11e5-8a2f-25e67cd7cd46.PNG)

What I am missing here, How to fix it

**Comment by psenechal** [comment]
This theme does not modify the Tag Cloud shape at all. If you use Shape Tracing, can you track down the shape that is being used to render the results?

**Comment by RajneeshVerma** [comment]
I fixed this issue, but i can see that ul and li in the content are not rendered correctly, working on it.

**Comment by psenechal** [comment]
The ul/li structure is correct...if you want the results formatted in a different manner than a list, you can add css styling or override the shape (Parts.TagCloud.cshtml)
