### ISSUE TITLE
Wrong swatches path on development machine

### ISSUE THREAD

**Issue by Devqon** [psenechal/PJS.Bootstrap#2]
While developing locally, the theme settings view is trying to find all swatches by enumerating the /Swatches map path, but when using locally (Visual Studio IIS Express) it maps to a wrong path:

Could not find a part of the path 'C:\Users\<name>\Documents\My Web Sites\Orchard.Web-Site(1)\Themes\PJS.Bootstrap\Content\Swatches'.

**Comment by psenechal** [comment]
The code is configured to use the root path of the website:

var swatchPath = Href("~/Themes/PJS.Bootstrap/Content/Swatches");

Where is your website publishing to when running locally?

**Comment by Devqon** [comment]
Not sure why, but when cloning the repo instead of downloading the zip it seems to work
