### ISSUE TITLE
BeforeMain zone

### ISSUE THREAD

**Issue by Devqon** [psenechal/PJS.Bootstrap#3]
There isn't any zone available which has the full width of the container. If I add a widget in the Featured or BeforeMain, it will be full width. The next available zone is Messages, but that zone will have the same width as the (before)content.

I would like to see a zone that has the full container width, and is placed before any content (so has the width of AsideFirst + Content + AsideSecond)

**Comment by psenechal** [comment]
The Featured and BeforeMain zones were purposely left open to allow you to put full-width items in them, such as a full-width slider. If you need to put an object in one of these zones that has the container width, simply wrap the shape with a div that has class="container". You can do this by overriding whatever shape is being rendered in that zone, or if you're adding content using the Layouts module, just add the class to the Layout object.
