### ISSUE TITLE
When swatch is changed/updated, theme is not synced across cached  pages

### ISSUE THREAD

**Issue by t9creative** [psenechal/PJS.Bootstrap#4]
Is there a way to clear the cache when a different swatch is selected and saved?  Currently when you select a different swatch, it takes various times across pages to clear, therefore some pages may be referencing the older selected swatch and some pages may show the new one.

**Comment by psenechal** [comment]
Are you using the Warmup module? If so, you can regenerate the warmup pages by clicking on Settings => Performance, then clicking on the Save button. The static warmup pages will be regenerated.
