### ISSUE TITLE
Missing Orchard namespaces after adding the theme

### ISSUE THREAD

**Issue by Alundra06** [psenechal/PJS.Bootstrap#6]
Bunch of missing orchard dlls after installing the theme.
Orchard.Core and HttpUtility
![orchard bootstrap theme issue](https://cloud.githubusercontent.com/assets/10134892/12877056/9027cb88-cdda-11e5-8999-be02c57edc11.PNG)

**Comment by psenechal** [comment]
Rebuild the project, then rebuild the solution.
